version: "3.1"

services:
  flask:
    image: flask
    restart: always
    environment:
      - SCRIPT=combined.py
    volumes:
      - "./models/:/app/models/"
      - "./data/:/app/data/"
    network_mode: bridge
